### ISSUE TITLE
Set it up

### ISSUE THREAD

**Issue by leomp12** [ecomplus/storefront-ci#1]
1. `git subtree add https://github.com/thiagoabreudev/storefront-ci master`;
2. Deploy on modules server;

**Comment by leomp12** [comment]
Also add nginx proxy locations to handle Netlify Identity Widget (with custom URLs) for CMS login:
https://github.com/hfte/netlify-cms-with-selfhosted-gotrue-and-git-gateway#make-it-work-with-netlify-cms

```yml
identity_url: "https://gotrue.e-com.plus/10111/identity"
gateway_url: "https://gitgateway.e-com.plus/1011/git"
accept_roles:
  - admin
  - s1011
```

```nginx
location ~ /(?<store>[0-9]+)/identity/ {
  proxy_redirect   off;
  proxy_set_header Host               $http_host;
  proxy_set_header X-Real-IP          $remote_addr;
  proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto  $scheme;
  proxy_set_header X-Store-ID         $store;
  proxy_pass http://gotrue/;
}
```
